### ISSUE TITLE
pull setup for ATX cases

### ISSUE THREAD

**Issue by dbx10** [Tesla-Cooler/tesla-cooler-mechanical#1]
I think it would be better to pull air from the back with an enclosed "fan box" covering all PCI-E slots. Simpler design, and can be adapted to most cases. 

Props to your work so far, but it seems to me like an extremely complicated project that two 80mm fans could easily solve.

Like this TYAN case here: https://youtu.be/zQzu7IGhqCQ?t=419

**Comment by esologic** [comment]
Yeah but then you have a weird thing hanging off the back of your computer ;) 

This is a much cleaner approach, and if time is a factor this is probably what people should be going for. Thanks for bringing this up @dbx10.
